import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Form from "../components/Form";
import Order from "../components/Order";
import logo from "../public/images/payqart-logo1.svg";

export default function Home() {
  const requestedAmount = "80,500";
  return (
    <div className="">
      <Head>
        <title>PayQart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="row">
          <div className="col-md-6">
            <div className="row">
              <div className={`${styles.col1} pt-5 container col-md-6`}>
                <div className={styles.overlay}></div>
                <div style={{ position: "relative" }} className="container">
                  <h5 className=" text-white text-start">
                    &#8592; &nbsp;Back To Store
                  </h5>
                  <div className="text-center" style={{ marginTop: "17rem" }}>
                    <Image
                      className={styles.filterGreen}
                      src={logo}
                      alt="logo"
                    />
                    <h5
                      style={{
                        marginTop: "0 !important",
                        fontFamily: "'DM Sans', sans-serif !important",
                      }}
                      className="text-white"
                    >
                      <em>You shop, we pay</em>
                    </h5>
                  </div>
                </div>
              </div>
              <div className={`${styles.col2} container pt-5 col-md-6`}>
                <Order requestedAmount={requestedAmount} />
              </div>
            </div>
          </div>
          <div className="col-md-6 text-center pt-5">
            <Form requestedAmount={requestedAmount} />
          </div>
        </div>
      </main>
    </div>
  );
}
